### ISSUE TITLE
Implement Navbar and Sidebar

### ISSUE THREAD

**Issue by malaythakur** [malaythakur/Sentra#1]

**Comment by JanumalaAkhilendra** [comment]
I would love to work on this assign it to me .

**Comment by malaythakur** [comment]
Thanks a lot for your interest! @JanumalaAkhilendra 

I'm almost done with the navbar and sidebar work, but I really appreciate your enthusiasm. There are other issues where your help would be great. please check - https://github.com/malaythakur/Horizon-Minds/issues
