### ISSUE TITLE
Design Database Schema 

### ISSUE THREAD

**Issue by malaythakur** [malaythakur/Sentra#3]

**Comment by lakshita10341** [comment]
can you assign me this issue

**Comment by malaythakur** [comment]
Thanks for your interest in working on this. I've assigned the issue to you.

**Comment by lakshita10341** [comment]
can you elaborate about this issue or your app

**Comment by malaythakur** [comment]
We have set up the initial schema using a SQL diagram tool (DrawSQL) to chart the data models before creating the database.
 
 Key Models & Schemas:

- Products: Contains information about the products, such as product_id, name, price, and stock_quantity.

- Sales & Purchases: Separate schemas for recording sales and purchase transactions. Each sale or purchase links back to a product using product_id.

- Sales & Purchase Summaries: These tables store summary data, like total sales or purchases, which helps in faster reporting without overloading the database.

- Expenses: Tracks expenses by category, with a summary table for efficient reporting on expense breakdowns.

Task Breakdown:

- Use DrawSQL or another diagramming tool to design the schema.
- Ensure each model includes appropriate primary keys, foreign keys, and necessary fields.
- Simplify relationships between models (e.g., one-to-many relationships between products and sales/purchases).

**Comment by lakshita10341** [comment]
Where should I add the link

**Comment by malaythakur** [comment]
Add it here, later we will add it in README.md

**Comment by lakshita10341** [comment]
https://lucid.app/lucidchart/086d0445-8d39-4c35-a2fd-6f25d027553a/edit?viewport_loc=-1585%2C-263%2C2487%2C1284%2C0_0&invitationId=inv_037f1142-cdcc-48a0-8770-411e04665091

**Comment by malaythakur** [comment]
Ideal Data Modelling. Download this data model as jpg and Create a PR  on branch [2-design-database-schema].

Your contribution is highly appreciated as this is the part where the entire application rests.

**Comment by lakshita10341** [comment]
#4 raised the PR. Please review it
